SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

SELECTION_RADIUS = 50
SELECTION_DECAY_TIMER = 5

PARTICLE_DECAY = 0.25
PARTICLE_SPEED = 50

DAMAGE_ALERT_LIFESPAN = 1
DAMAGE_ALERT_WIDTH = 80
DAMAGE_ALERT_HEIGHT = 40

HIT_COOLDOWN = 0.25

PLAYER_RADIUS = 25
PLAYER_HEALTH = 500
PLAYER_MOVESPEED = 100
PLAYER_TURN_SPEED = 150
PLAYER_DETECTION_RANGE = 500 

ENEMY_RADIUS = 10
ENEMY_MAX_HEALTH = 10
ENEMY_MOVE_SPEED = 300
ENEMY_TURN_SPEED = 200
ENEMY_DETECTION_RANGE = 300
ENEMY_DAMAGE_VALUE = 25

SPAWN_COOLDOWN = 0.25
SPAWNER_MULTIPLIER = 500

BASIC_BULLET_RADIUS = 3
BASIC_BULLET_VELOCITY = 800
BASIC_BULLET_DAMAGE = 4
BASIC_BULLET_LIFESPAN = 0.7
BASIC_BULLET_KNOCKBACK = 1

#MINIGUN_ARC = 30
MINIGUN_ARC = 0
#MINIGUN_ROF = 1
MINIGUN_ROF = 0.05

BASIC_LASER_LENGTH = 400
BASIC_LASER_LIFESPAN = 0.2
BASIC_LASER_DAMAGE = 10
BASIC_LASER_KNOCKBACK = 0.1